theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  search:
    active: false  
    params:
  logo:
    header: "/assets/images/logo.png"
    footer: "/assets/images/footer.png"